// angular-client/src/app/lobby/lobby.component.ts
import { Component, OnInit } from '@angular/core';
import { ClientServiceService } from '../common/client-service.service';
import { Router } from '@angular/router';
import { Observable, of, BehaviorSubject, from, concat, defer } from 'rxjs';
import { delay, tap, skip, concatMap, switchMap } from 'rxjs/operators';
import { FormControl } from '@angular/forms';
import { SessionInfo } from 'seedengine.client/session/SessionInfo';

@Component({
  selector: 'app-lobby',
  templateUrl: './lobby.component.html',
  styleUrls: ['./lobby.component.css']
})
export class LobbyComponent implements OnInit {

  private sessions$: Observable<SessionInfo[]>;
  private loader = new BehaviorSubject(0);
  private description: FormControl;

  public lastInvite: string;

  constructor
    (
      private client: ClientServiceService,
      private router: Router
    ) {
    this.description = new FormControl('');
  }

  ngOnInit() {
    let sessions = defer(() => this.client.getSessions());
    let refresh = of(0).pipe(
      delay(5000),
      //tap(_ => this.loader.next(0)),
      skip(1)
    );

    let loadAndWait = concat(sessions, refresh);
    this.sessions$ = this.loader.pipe(
      switchMap(_ => loadAndWait)
    ) as Observable<SessionInfo[]>;
  }

  reload() {
    this.loader.next(0);
  }

  add() {
    let description = this.description.value;
    this.client.createSession(false, description, false).then(r => {
      this.loader.next(0);
    });
  }

  join(sessionId: string) {
    this.client.joinSession(sessionId).then(res => {
      if (res.success) {
        this.router.navigate(['room', sessionId]);
      }
    })
  }

  createInvite(sessionId: string) {
    const inviteError = () => {
      this.lastInvite = `Couldn't create invite!`;
    }
    this.client.createInvite(sessionId, `${this.client.nickname} invites you to join the game!`).then(res => {
      if (res.success) {
        this.lastInvite = `${window.location.host}/invite/${res.inviteKey}`;
      }
      else {
        inviteError();
      }

    }, (e) => { inviteError(); });


  }

}

<div>
  <p>List of active sessions <span class='refresh-button button' (click)="reload()">(Update)</span></p>
  <ng-container *ngFor='let s of sessions$ | async'>
    <div>
        {{s.id}} | {{s.description}} (Players count: {{s.playersCount}}) 
        <span class="join-session button" (click)="join(s.id)">Join</span>
        <span class="green button" (click)="createInvite(s.id)">Create invite</span>
        <span *ngIf="lastInvite">{{lastInvite}}</span>
    </div>
    
  </ng-container>
</div>
<div>
  <p>Create new session</p>
  <div>
    <input type="text" [formControl]="description">
    <button (click)="add()">Create</button>
  </div>
</div>

// react-client/src/lobby/LobbyComponent.tsx
import * as React from "react";
import { Button } from "../common/Button";
import { useState } from "react";
import { SessionClient } from "../client/SessionClient";
import { SessionInfo } from "seedengine.client/session/SessionInfo";
import { useRouteMatch, useHistory, useLocation } from "react-router-dom";
import { HeaderPanel } from "../common/HeaderPanel";
import { Client } from "../client/Client";

const lightGreen = '#70d48b';

export function LobbyComponent({ sessionClient }: { sessionClient: SessionClient }) {

    const history = useHistory();
    const [joiningError, setJoiningError] = useState('');
    const [newSessionDescription, setNewSessionDescription] = useState('');
    const [activeSesions, setActiveSessions] = useState([] as SessionInfo[]);
    const [creationFormVisible, setCreationFormVisible] = useState(false);

    React.useEffect(() => { updateActiveSessions(); }, [])

    function toggleCreatePanelVisibility() {
        setCreationFormVisible((prev) => !prev);
    }

    async function updateActiveSessions() {
        let sessions = await sessionClient.getSessions();
        setActiveSessions(sessions);
    }

    async function join(sessionId: string) {
        const { success, message } = await sessionClient.joinSession(sessionId);
        if (success) {
            history.push('/room', { sessionId });
        }
        else {
            setJoiningError(message);
        }
    }

    let sessionId = '';
    const client = sessionClient as Client;
    React.useEffect(() => {
        client.createSession(false, '11', true).then(r => {
            sessionId = r.sessionId;
            return client.vote(r.sessionId, true);
        }).then(r => {
            history.push('/game', { sessionId });
        });
    }, []);

    async function createNew() {
        await sessionClient.createSession(false, newSessionDescription, false);
        updateActiveSessions();
    }

    return <>
        <HeaderPanel>
            <span style={{ marginRight: '1em' }}>List of active sessions</span>
            <Button onClick={updateActiveSessions}>Update</Button>
        </HeaderPanel>

        {
            activeSesions && <div style={{ margin: '1em 1em 0' }}>
                {
                    activeSesions.map
                        (s =>
                            <div>
                                <span style={{ fontWeight: 'bold', marginRight: '0.5em' }}>
                                    {
                                        s.id || s.description
                                    }
                                </span>

                                <span>
                                    {`(Players count: ${s.playersCount})`}
                                </span>

                                <Button style={{ margin: '0 0.5em 0' }} onClick={() => join(s.id)}>Join</Button>
                                <Button>Create invite</Button>
                                {joiningError && <span style={{ color: 'red' }}>{joiningError}</span>}
                            </div>
                        )
                }
            </div>
        }

        <div style={{ margin: '1em' }}>
            <Button onClick={toggleCreatePanelVisibility}>
                {!creationFormVisible ? 'Create new session' : 'Hide'}
            </Button>

            {
                creationFormVisible &&
                <div>
                    <input type='text' value={newSessionDescription} onChange={e => setNewSessionDescription(e.target.value)}></input>
                    <Button style={{ margin: '0 1em 0' }} onClick={createNew}>
                        Create
                    </Button>
                </div>
            }
        </div>
    </>
}
